"""
This module was autogenerated by gale.
"""
import settings
from src.forest_defenders import ForestDefenders

if __name__ == '__main__':
    game = ForestDefenders(
        "Forest Defenders",
        settings.WINDOW_WIDTH, settings.WINDOW_HEIGHT,
        settings.VIRTUAL_WIDTH, settings.VIRTUAL_HEIGHT
    )
    game.exec()
