"""
This module was autogenerated by gale.
"""
import pathlib

import pygame

from gale import frames
from gale import input_handler

from moviepy.editor import VideoFileClip


input_handler.InputHandler.set_keyboard_action(input_handler.KEY_ESCAPE, 'quit')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RETURN, "confirm")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RIGHT, "move_right")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_LEFT, "move_left")
input_handler.InputHandler.set_mouse_click_action(input_handler.MOUSE_BUTTON_1, "click")
input_handler.InputHandler.set_mouse_click_action(input_handler.MOUSE_BUTTON_3, "right_click")

input_handler.InputHandler.set_mouse_wheel_action(input_handler.MOUSE_WHEEL_UP,"zoom_in")
input_handler.InputHandler.set_mouse_wheel_action(input_handler.MOUSE_WHEEL_DOWN,"zoom_out")

#abilidades
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_q,"q")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_w,"w")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_e,"e")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_r,"r")


#map dimensions
MAP_WIDTH= 2048
MAP_HEIGHT =  768

#dimensiones de la arena
ARENA_WIDTH = 960
ARENA_HEIGHT = 1080

BULLET_WIDTH = 8
BULLET_HEIGHT = 8

# Size we want to emulate
VIRTUAL_WIDTH = 320 *2
VIRTUAL_HEIGHT = 180 *2
# Size of our actual window
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

SCALE_X = VIRTUAL_WIDTH /WINDOW_WIDTH
SCALE_Y = VIRTUAL_HEIGHT /WINDOW_HEIGHT

ROBOT_WIDTH = 48
ROBOT_HEIGHT = 48

FINALBOSS_WIDTH = 96
FINALBOSS_HEIGHT = 96

DRON_WIDTH =37
DRON_HEIGHT = 30

LASER_WIDTH = 1280
LASER_HEIGHT = 50

BASE_DIR = pathlib.Path(__file__).parent

# Register your textures from the graphics folder, for instance:
background_image = pygame.image.load(BASE_DIR / "assets" / "graphics" / "background.png")
background_image = pygame.transform.scale(background_image, (VIRTUAL_WIDTH, VIRTUAL_HEIGHT))

TEXTURES = {
    'background': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"background.png"),
    'mouse': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"pointer.png"),
    'logo': pygame.image.load(BASE_DIR / "assets" / "graphics" / "logo.png"),
    'play_button': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"play.png"),
    'instructions_button': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"instructions.png"),
    'quit_button': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"quit.png"),
    'play_selected': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"play_selected.png"),
    'instructions_selected': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"instructions_selected.png"),
    'quit_selected': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"quit_selected.png"),
    'Level_1': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"Level_1.png"),
    'Level_2': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"Level_2.png"),
    'Level_3': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"Level_3.png"),
    'Level_2_b': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"Level_2_b.png"),
    'Level_3_b': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"Level_3_b.png"),
    'wild_robot': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"robot.png"),
    'dron1_bullet': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"balita.png"),
    'dron1': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"texture_dron.png"),
    'shield': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"shield.png"),
    'H0': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_0.png"),
    'H1': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_1.png"),
    'H2': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_2.png"),
    'H3': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_3.png"),
    'H4': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_4.png"),
    'H5': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_5.png"),
    'H6': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_6.png"),
    'H7': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_7.png"),
    'H8': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_8.png"),
    'H9': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_9.png"),
    'H10': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_10.png"),
    'HHIT': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"healthbar"/"VIDA_HIT.png"),
    'explosions': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"explosion.png"),
    'finalboss': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"FinalBoss.png"),
    'blue_laser': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"blue_laser.png"),
    'red_laser': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"red_laser.png"),
    'chick': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"animals"/"chick.png"),
    'chicken': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"animals"/"chicken.png"),
    'duck': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"animals"/"duck.png"),
    'crocodile': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"animals"/"crocodile.png"),
    'frog': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"animals"/"frog.png"),
    'pig': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"animals"/"pig.png"),
    'moose': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"animals"/"moose.png"),
    'bear': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"animals"/"bear.png"),
    'goat': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"animals"/"goat.png"),
    'arena': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"arena_1.png"),
    'win': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"win.png"),
    'instruction': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"instruction.png"),
    'gameover': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"gameover.png"),
    'q_cd': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"cooldowns"/"q_cd.png"),
    'q_not_cd': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"cooldowns"/"q_not_cd.png"),
    'w_cd': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"cooldowns"/"w_cd.png"),
    'w_not_cd': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"cooldowns"/"w_not_cd.png"),
    'e_cd': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"cooldowns"/"e_cd.png"),
    'e_not_cd': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"cooldowns"/"e_not_cd.png"),
    'fireball1': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"fireball1.png"),
}

# TILEMAPS = {

#     'Level_1_map': BASE_DIR / "assets" / "tile_maps" / "Level1_map.tmx",
# }

FRAMES = {
    "explosion": frames.generate_frames(TEXTURES["explosions"],30,29)
}

pygame.mixer.init()

# Register your sound from the sounds folder, for instance:
# SOUNDS = {
#     'my_sound': pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "my_sound.wav"),
# }
SOUNDS = {
    #"arena": pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "arena.mp3"),
    #"level_1": pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "level_1.wav"),
    #"level_2": pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "level_2.mp3"),
    #"level_3": pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "level_3.mp3"),
    "win": pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "win.mp3"),
    "laser_charge": pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "laser_charge.mp3"),
    "laser_shoot": pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "laser_shoot.wav"),
    "drone_explode": pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "drone_explode.wav"),
    
}

pygame.font.init()

# Register your fonts from the fonts folder, for instance:
FONTS = {
    'large': pygame.font.Font(BASE_DIR / "assets"  / "fonts" / "EagleLake-Regular.ttf", 12),
    'start_menu': pygame.font.Font(BASE_DIR / "assets"  / "fonts" / "EagleLake-Regular.ttf", 6),
    'extra_large': pygame.font.Font(BASE_DIR / "assets"  / "fonts" / "EagleLake-Regular.ttf", 20),
}

# Register your videos from the videos folder, for instance:
# VIDEOS = {
#     'my_video': pygame.movie.Movie(str(BASE_DIR / "assets"  / "videos" / "my_video.mp4")),
# }
VIDEOS = {

    'level_1_vid' : VideoFileClip(str(BASE_DIR / "assets" / "videos" / "Level_1_banner.mp4")),
    'level_2_vid' : VideoFileClip(str(BASE_DIR / "assets" / "videos" / "Level_2_banner.mp4")),
    'level_3_vid' : VideoFileClip(str(BASE_DIR / "assets" / "videos" / "Level_3_banner.mp4")),
    'intro': VideoFileClip(str(BASE_DIR / "assets" / "videos" / "intro.mp4")),
}
